/run/initialize

/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0. 0. 500. km
/gps/ang/type cos
/gps/energy {i} keV # Sweep

/analysis/h1/setActivationToAll true
#/analysis/h1/setActivation 36 true
#/analysis/h1/setActivation 536 true
#/analysis/h1/setActivation 1036 true

# we ran it on this for the low energies
/run/beamOn 50000000


/control/shell mkdir /home/patrick/phd/build/msis_xray_build/ramdisk/{i}
/control/shell mv -f /home/patrick/phd/build/msis_xray_build/ramdisk/*.csv /home/patrick/phd/build/msis_xray_build/ramdisk/{i}



#/control/shell mv -f /home/patrick/phd/build/msis_xray_build/ramdisk/events_run_0_h1_photon_KE_histogram_atm_slc_1035.csv /home/patrick/phd/build/msis_xray_build/ramdisk/output_h1_photon_KE_histogram_xtal_{i}_keV.csv
#/control/shell mv -f /home/patrick/phd/build/msis_xray_build/ramdisk/events_run_0_h1_photon_theta_histogram_atm_slc_35.csv /home/patrick/phd/build/msis_xray_build/ramdisk/output_h1_photon_eDep_histogram_xtal_{i}_keV.csv
#/control/shell mv -f /home/patrick/phd/build/msis_xray_build/ramdisk/events_run_0_h1_photon_phi_histogram_atm_slc_535.csv /home/patrick/phd/build/msis_xray_build/ramdisk/output_h1_photon_theta_histogram_xtal_{i}_keV.csv
