/run/numberOfThreads 1
/control/verbose 2
/control/saveHistory
/run/verbose 2

/run/initialize

# Init general particle source
/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0. 0. 500. km
/gps/ang/type beam1d
/gps/energy 300 keV
/gps/direction 0 0 -1

/run/printProgress 1000
/run/beamOn 1000000
/control/shell mv /home/mrpatric/mbeam_build/events_run_?_h1_photon_KE_histogram_atm_slc_34.csv /home/mrpatric/mbeam_build/events_run_?_h1_photon_KE_histogram_atm_slc_34.csv

