# given a cosine beam of N e- / cm^2 / sec, how many X-rays come out the bottom
# of the atmosphere? What happens when you perturb the beam?

# Init general particle source
/run/initialize
/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0. 0. 500. km # 250 km here is a half length, maps to 500 km AGL
/gps/ang/type cos
#/gps/ang/type beam1d
#/gps/direction 0 0 -1

# this is the best determined energy spectrum from curve-fitting
# g4nlm[100, 600, 810]
#/gps/energy 500 keV # Sweep

/gps/ene/type Exp
/gps/ene/min {i} keV
/gps/ene/max 10 MeV
/gps/ene/ezero .810 MeV

/control/verbose 2
/run/verbose 2

/analysis/h1/setActivationToAll false # all histograms are on
##/analysis/h1/setActivation 36 true
#/analysis/h1/setActivation 536 true
#/analysis/h1/setActivation 1036 true

/score/create/boxMesh boxMesh_{i}
/score/mesh/boxSize 10000. 10000. 250. km
/score/mesh/nBin 1 1 500
/score/mesh/translate/xyz 0. 0. 0. km
/score/quantity/flatSurfaceCurrent fSC
/score/filter/particle gammafilter gamma


/run/beamOn 100000
/score/close
/score/dumpQuantityToFile boxMesh_{i} fSC N_lowercutoff_{i}_MeV.csv
