/control/verbose 2
/control/saveHistory
/run/verbose 2

/run/initialize

# Init general particle source
/gps/particle e-
/gps/pos/type Point
/gps/pos/centre 0. 0. 500. km
/gps/ang/type beam1d
/gps/energy 500 keV
/gps/direction 0 0 -1

# Use this open statement to create an OpenGL view:
/vis/open OGL

# Draw geometry:
/vis/drawVolume

# Specify view angle:
/vis/viewer/set/viewpointThetaPhi 90. 0.
/vis/viewer/refresh

/vis/viewer/set/style wireframe

# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth

/vis/modeling/trajectories/select drawByCharge -1
/vis/scene/endOfEventAction accumulate 1


# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings

/vis/viewer/zoom 1000

/run/printProgress 10000
/run/beamOn 100000
